---
title: "Manipulating and Plotting Data"
subtitle: "Coding for Reproducible Research"
author: "Laura Roldan-Gomez"
date: today
format:
  revealjs:
    scrollable: true
    highlight-style: arrow-light
    slide-number: c/t
    footer: "[Coding for Reproducible Research](https://uniexeterrse.github.io/workshop-homepage/)"
    theme: default
editor: visual
---

# We are...

<br>

Emma Walker

<br>

Theresa Wacker

<br>

Laura Roldan-Gomez

lr480@exeter.ac.uk

# **Welcome again to this hybrid session!** {background-opacity="0.5" background-image="images/wave.jpg"}

Last week was tough!

# Today...

-   A quick word on matrices

-   Working with what we learned on the previous session:

-   Data Exploration

-   Data Manipulation

-   Plotting!!!

# **Let's reflect**

**So far you've...**

-   Installed R and Rstudio, know its parts, how to open a script.

-   Learned there are three core data types:

    -   Numerical: 3 15.5 1+4i
    -   Characters or strings: "a" "I love R" "3"\
    -   Logical: TRUE or FALSE 1 or 0

## 

-   Learned that these data types can be organised into
    -   Vectors
    -   Lists
    -   Data frames


## Let's begin {background-opacity="0.5" background-image="images/graphs.jpeg"}

## Next week...

In Session 4 - Introduction to Statistical Analysis, you will learn...

-   Summary statistics
-   Normal and other distributions
-   Confidence Intervals
-   Random Sampling
-   Basic analysis
-   Correlation
-   T-test
-   ANOVA

## Congratulations this is the END! {background="#000000"}

::: {style="position:relative; padding-bottom:calc(87.50% + 44px)"}
<iframe src="https://gfycat.com/ifr/EverlastingWelloffGenet" frameborder="0" scrolling="no" width="50%" height="50%" style="position:absolute;top:0;left:0;">

</iframe>
:::

<p><a href="https://gfycat.com/everlastingwelloffgenet-nintendo-level-mario-1-1-nes-smb">via Gfycat</a></p>

## 

This was hard but do keep going. Join us for Session 3 - Manipulating and Plotting Data. Hopefully, you will find it easier than today.

-   Thank **YOU**! For your attention and effort

-   Be a part of this! You can helps us running or assisting a future session (they can )opt into this via the feedback survey)

-   Tell us... What you liked and what you didn't using the feedback survey
