---
title: "Introduction to Statistical Analysis"
subtitle: "Coding for Reproducible Research"
author: "Laura Roldan-Gomez"
date: today
format:
  revealjs:
    scrollable: true
    highlight-style: arrow-light
    slide-number: c/t
    footer: "[Coding for Reproducible Research](https://uniexeterrse.github.io/workshop-homepage/)"
    theme: default
editor: visual
---

# We are...

<br>

Emma Walker

<br>

Xinran Du

xd247\@exeter.ac.uk

<br>

Laura Roldan-Gomez

lr480\@exeter.ac.uk

# **Welcome to the LAST session!** {background-opacity=0.7 background-image="images/graphs.jpeg"}

# Now you know...

Or are familiar with...

- how to explore your data: subsetting, matching elements, merging and binding
- manipulating data: paste(), rename elements, use the seq() function
- visualise data: type of plots and how to make them, how to plot on top of plots, add to your plot, manipulate margins, composite plots and exporting your plots

## Today

-   Summary statistics
-   Normal and other distributions
-   Confidence Intervals
-   Random Sampling
-   Basic analysis
-   Correlation
-   T-test
-   ANOVA

## Expectations for today

- We cannot teach statistics and R in 3 hours
- This is not a statistics course
- I am not a statistics expert

## Congratulations and keep going! {background="#000000"}

Big Thank **YOU**! 

-   Be a part of this! You can helps us running or assisting a future session (they can )opt into this via the feedback survey)

-   Tell us... What you liked and what you didn't using the feedback survey

- Please sign the attendance sheet.
